moonship:

  strategies:
    test:
      algo: moonship.algo.test.LogMarketInfo
      markets:
        - bitcoin
    other:
      algo: moonship.algo.other.OtherAlgo
      markets:
        - bitcoin
        - other

  markets:
    bitcoin:
      symbol: BTCUSD
      client: moonship.client.test.TestClient
      feed: moonship.client.test.TestDataFeed
    other:
      symbol: OTHER
      client: moonship.client.other.OtherClient
      feed: moonship.client.other.OtherDataFeed

  logging:
    root:
      handlers:
        - stdout
        - file
    loggers:
      moonship:
        level: INFO
    handlers:
      stdout:
        class: logging.StreamHandler
        formatter: log
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: log
        filename: log/moonship.log
        maxBytes: 1024
        backupCount: 3
    formatters:
      log:
        format: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
