moonship:

  strategies:
    test:
      algo: moonship.strategy.test.LogMarketInfo
      markets:
        - bitcoin
    other:
      algo: moonship.strategy.other.OtherAlgo
      markets:
        - bitcoin
        - other

  markets:
    bitcoin:
      symbol: BTCUSD
      client: moonship.market.test.Client
      feed: moonship.market.test.DataFeed
    other:
      symbol: OTHER
      client: moonship.market.other.Client
      feed: moonship.market.other.DataFeed

  logging:
    root:
      handlers:
        - stdout
        - file
    loggers:
      moonship:
        level: INFO
    handlers:
      stdout:
        class: logging.StreamHandler
        formatter: log
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: log
        filename: log/moonship.log
        maxBytes: 1024
        backupCount: 3
    formatters:
      log:
        format: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
