moonship:

  api:
    port: 443
    ssl_cert: cert.pem
    ssl_key: key.pem
    user: ms
    password: $2b$12$JyIZJl9BZgKXX8fXAQHdVOGiaGwuTf.xglYajD4EJuPuK13RP0dRi

  strategies:
    test:
      algo: moonship.algo.test.LogMarketInfo
      markets:
        - bitcoin
    other:
      algo: moonship.algo.other.OtherAlgo
      markets:
        - bitcoin
        - other

  markets:
    bitcoin:
      symbol: BTCUSD
      client: moonship.client.test.TestClient
    other:
      symbol: OTHER
      client: moonship.client.other.OtherClient

  redis:
    url: rediss://:password@localhost:6379
    ssl_verify_cert: true

  logging:
    root:
      handlers:
        - stdout
        - file
    loggers:
      moonship:
        level: INFO
    handlers:
      stdout:
        class: logging.StreamHandler
        formatter: log
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: log
        filename: log/moonship.log
        maxBytes: 1024
        backupCount: 3
    formatters:
      log:
        format: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
