moonship:

  api:
    port: 443
    ssl_cert: cert.pem
    ssl_key: key.pem
    user: ms
    password: $2b$12$JyIZJl9BZgKXX8fXAQHdVOGiaGwuTf.xglYajD4EJuPuK13RP0dRi

  strategies:
    test:
      algo: moonship.algo.test.LogMarketInfo
      auto_start: true
      markets:
        - bitcoin
    other:
      algo: moonship.algo.other.MyOtherAlgo
      auto_start: false
      markets:
        - bitcoin
        - solana
    paper-trade:
      algo: moonship.algo.other.MyOtherAlgo
      auto_start: false
      markets:
        - bitcoin-paper

  markets:
    bitcoin:
      symbol: BTCUSDT
      client: moonship.client.binance.BinanceClient
      candle_period: 60
    bitcoin-paper:
      symbol: BTCUSDT
      client: moonship.client.paper.PaperTradingClient
      real_client: moonship.client.binance.BinanceClient
      candle_period: 60
    solana:
      symbol: SOLUSDT
      client: moonship.client.binance.BinanceClient
      candle_period: 60

  redis:
    url: rediss://:password@localhost:6379
    ssl_verify_cert: true

  logging:
    root:
      handlers:
        - stdout
        - file
    loggers:
      moonship:
        level: INFO
    handlers:
      stdout:
        class: logging.StreamHandler
        formatter: log
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: log
        filename: log/moonship.log
        maxBytes: 1024
        backupCount: 3
    formatters:
      log:
        format: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
